apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: metrics-mock
  name: metrics-mock
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics-mock
  template:
    metadata:
      labels:
        app.kubernetes.io/component: metrics-mock
    spec:
      containers:
      - image: metrics-mock
        imagePullPolicy: IfNotPresent
        name: metrics-mock
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/component: metrics-mock
  name: metrics-mock
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: metrics-mock
  sessionAffinity: None
  type: ClusterIP