// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for playwright metrics.
type MetricsConfig struct {
	PlaywrightPageDocumentCount        MetricConfig `mapstructure:"playwright.page.document.count"`
	PlaywrightPageDomNodeCount         MetricConfig `mapstructure:"playwright.page.dom_node.count"`
	PlaywrightPageFrameCount           MetricConfig `mapstructure:"playwright.page.frame.count"`
	PlaywrightPageJsEventListenerCount MetricConfig `mapstructure:"playwright.page.js_event_listener.count"`
	PlaywrightPageJsHeapTotalSize      MetricConfig `mapstructure:"playwright.page.js_heap.total_size"`
	PlaywrightPageJsHeapUsedSize       MetricConfig `mapstructure:"playwright.page.js_heap.used_size"`
	PlaywrightPageLayoutCount          MetricConfig `mapstructure:"playwright.page.layout.count"`
	PlaywrightPageLayoutDuration       MetricConfig `mapstructure:"playwright.page.layout.duration"`
	PlaywrightPageRecalcStyleCount     MetricConfig `mapstructure:"playwright.page.recalc_style.count"`
	PlaywrightPageRecalcStyleDuration  MetricConfig `mapstructure:"playwright.page.recalc_style.duration"`
	PlaywrightPageScriptDuration       MetricConfig `mapstructure:"playwright.page.script.duration"`
	PlaywrightPageTaskDuration         MetricConfig `mapstructure:"playwright.page.task.duration"`
	PlaywrightTargetsCount             MetricConfig `mapstructure:"playwright.targets.count"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		PlaywrightPageDocumentCount: MetricConfig{
			Enabled: true,
		},
		PlaywrightPageDomNodeCount: MetricConfig{
			Enabled: true,
		},
		PlaywrightPageFrameCount: MetricConfig{
			Enabled: true,
		},
		PlaywrightPageJsEventListenerCount: MetricConfig{
			Enabled: true,
		},
		PlaywrightPageJsHeapTotalSize: MetricConfig{
			Enabled: true,
		},
		PlaywrightPageJsHeapUsedSize: MetricConfig{
			Enabled: true,
		},
		PlaywrightPageLayoutCount: MetricConfig{
			Enabled: true,
		},
		PlaywrightPageLayoutDuration: MetricConfig{
			Enabled: true,
		},
		PlaywrightPageRecalcStyleCount: MetricConfig{
			Enabled: true,
		},
		PlaywrightPageRecalcStyleDuration: MetricConfig{
			Enabled: true,
		},
		PlaywrightPageScriptDuration: MetricConfig{
			Enabled: true,
		},
		PlaywrightPageTaskDuration: MetricConfig{
			Enabled: true,
		},
		PlaywrightTargetsCount: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for playwright metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
