// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					PlaywrightPageDocumentCount:        MetricConfig{Enabled: true},
					PlaywrightPageDomNodeCount:         MetricConfig{Enabled: true},
					PlaywrightPageFrameCount:           MetricConfig{Enabled: true},
					PlaywrightPageJsEventListenerCount: MetricConfig{Enabled: true},
					PlaywrightPageJsHeapTotalSize:      MetricConfig{Enabled: true},
					PlaywrightPageJsHeapUsedSize:       MetricConfig{Enabled: true},
					PlaywrightPageLayoutCount:          MetricConfig{Enabled: true},
					PlaywrightPageLayoutDuration:       MetricConfig{Enabled: true},
					PlaywrightPageRecalcStyleCount:     MetricConfig{Enabled: true},
					PlaywrightPageRecalcStyleDuration:  MetricConfig{Enabled: true},
					PlaywrightPageScriptDuration:       MetricConfig{Enabled: true},
					PlaywrightPageTaskDuration:         MetricConfig{Enabled: true},
					PlaywrightTargetsCount:             MetricConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					PlaywrightPageDocumentCount:        MetricConfig{Enabled: false},
					PlaywrightPageDomNodeCount:         MetricConfig{Enabled: false},
					PlaywrightPageFrameCount:           MetricConfig{Enabled: false},
					PlaywrightPageJsEventListenerCount: MetricConfig{Enabled: false},
					PlaywrightPageJsHeapTotalSize:      MetricConfig{Enabled: false},
					PlaywrightPageJsHeapUsedSize:       MetricConfig{Enabled: false},
					PlaywrightPageLayoutCount:          MetricConfig{Enabled: false},
					PlaywrightPageLayoutDuration:       MetricConfig{Enabled: false},
					PlaywrightPageRecalcStyleCount:     MetricConfig{Enabled: false},
					PlaywrightPageRecalcStyleDuration:  MetricConfig{Enabled: false},
					PlaywrightPageScriptDuration:       MetricConfig{Enabled: false},
					PlaywrightPageTaskDuration:         MetricConfig{Enabled: false},
					PlaywrightTargetsCount:             MetricConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
