// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0

			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightPageDocumentCountDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val", "target.url-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightPageDomNodeCountDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val", "target.url-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightPageFrameCountDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val", "target.url-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightPageJsEventListenerCountDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val", "target.url-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightPageJsHeapTotalSizeDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val", "target.url-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightPageJsHeapUsedSizeDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val", "target.url-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightPageLayoutCountDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val", "target.url-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightPageLayoutDurationDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val", "target.url-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightPageRecalcStyleCountDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val", "target.url-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightPageRecalcStyleDurationDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val", "target.url-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightPageScriptDurationDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val", "target.url-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightPageTaskDurationDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val", "target.url-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPlaywrightTargetsCountDataPoint(ts, 1, "playwright.endpoint-val", "target.type-val")

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			assert.Equal(t, 1, metrics.ResourceMetrics().Len())
			rm := metrics.ResourceMetrics().At(0)
			assert.Equal(t, res, rm.Resource())
			assert.Equal(t, 1, rm.ScopeMetrics().Len())
			ms := rm.ScopeMetrics().At(0).Metrics()
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, ms.Len())
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, ms.Len())
			}
			validatedMetrics := make(map[string]bool)
			for i := 0; i < ms.Len(); i++ {
				switch ms.At(i).Name() {
				case "playwright.page.document.count":
					assert.False(t, validatedMetrics["playwright.page.document.count"], "Found a duplicate in the metrics slice: playwright.page.document.count")
					validatedMetrics["playwright.page.document.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of documents in the page.", ms.At(i).Description())
					assert.Equal(t, "{document}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.url")
					assert.True(t, ok)
					assert.Equal(t, "target.url-val", attrVal.Str())
				case "playwright.page.dom_node.count":
					assert.False(t, validatedMetrics["playwright.page.dom_node.count"], "Found a duplicate in the metrics slice: playwright.page.dom_node.count")
					validatedMetrics["playwright.page.dom_node.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of DOM nodes in the page.", ms.At(i).Description())
					assert.Equal(t, "{node}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.url")
					assert.True(t, ok)
					assert.Equal(t, "target.url-val", attrVal.Str())
				case "playwright.page.frame.count":
					assert.False(t, validatedMetrics["playwright.page.frame.count"], "Found a duplicate in the metrics slice: playwright.page.frame.count")
					validatedMetrics["playwright.page.frame.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of frames in the page.", ms.At(i).Description())
					assert.Equal(t, "{frame}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.url")
					assert.True(t, ok)
					assert.Equal(t, "target.url-val", attrVal.Str())
				case "playwright.page.js_event_listener.count":
					assert.False(t, validatedMetrics["playwright.page.js_event_listener.count"], "Found a duplicate in the metrics slice: playwright.page.js_event_listener.count")
					validatedMetrics["playwright.page.js_event_listener.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of JavaScript event listeners in the page.", ms.At(i).Description())
					assert.Equal(t, "{listener}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.url")
					assert.True(t, ok)
					assert.Equal(t, "target.url-val", attrVal.Str())
				case "playwright.page.js_heap.total_size":
					assert.False(t, validatedMetrics["playwright.page.js_heap.total_size"], "Found a duplicate in the metrics slice: playwright.page.js_heap.total_size")
					validatedMetrics["playwright.page.js_heap.total_size"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total JavaScript heap size.", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.url")
					assert.True(t, ok)
					assert.Equal(t, "target.url-val", attrVal.Str())
				case "playwright.page.js_heap.used_size":
					assert.False(t, validatedMetrics["playwright.page.js_heap.used_size"], "Found a duplicate in the metrics slice: playwright.page.js_heap.used_size")
					validatedMetrics["playwright.page.js_heap.used_size"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Used JavaScript heap size.", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.url")
					assert.True(t, ok)
					assert.Equal(t, "target.url-val", attrVal.Str())
				case "playwright.page.layout.count":
					assert.False(t, validatedMetrics["playwright.page.layout.count"], "Found a duplicate in the metrics slice: playwright.page.layout.count")
					validatedMetrics["playwright.page.layout.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Cumulative count of full or partial page layouts.", ms.At(i).Description())
					assert.Equal(t, "{layout}", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.url")
					assert.True(t, ok)
					assert.Equal(t, "target.url-val", attrVal.Str())
				case "playwright.page.layout.duration":
					assert.False(t, validatedMetrics["playwright.page.layout.duration"], "Found a duplicate in the metrics slice: playwright.page.layout.duration")
					validatedMetrics["playwright.page.layout.duration"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Cumulative duration of page layout operations.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.url")
					assert.True(t, ok)
					assert.Equal(t, "target.url-val", attrVal.Str())
				case "playwright.page.recalc_style.count":
					assert.False(t, validatedMetrics["playwright.page.recalc_style.count"], "Found a duplicate in the metrics slice: playwright.page.recalc_style.count")
					validatedMetrics["playwright.page.recalc_style.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Cumulative count of CSS style recalculations.", ms.At(i).Description())
					assert.Equal(t, "{recalculation}", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.url")
					assert.True(t, ok)
					assert.Equal(t, "target.url-val", attrVal.Str())
				case "playwright.page.recalc_style.duration":
					assert.False(t, validatedMetrics["playwright.page.recalc_style.duration"], "Found a duplicate in the metrics slice: playwright.page.recalc_style.duration")
					validatedMetrics["playwright.page.recalc_style.duration"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Cumulative duration of CSS style recalculations.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.url")
					assert.True(t, ok)
					assert.Equal(t, "target.url-val", attrVal.Str())
				case "playwright.page.script.duration":
					assert.False(t, validatedMetrics["playwright.page.script.duration"], "Found a duplicate in the metrics slice: playwright.page.script.duration")
					validatedMetrics["playwright.page.script.duration"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Cumulative duration of JavaScript execution.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.url")
					assert.True(t, ok)
					assert.Equal(t, "target.url-val", attrVal.Str())
				case "playwright.page.task.duration":
					assert.False(t, validatedMetrics["playwright.page.task.duration"], "Found a duplicate in the metrics slice: playwright.page.task.duration")
					validatedMetrics["playwright.page.task.duration"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Cumulative duration of all tasks.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityCumulative, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.url")
					assert.True(t, ok)
					assert.Equal(t, "target.url-val", attrVal.Str())
				case "playwright.targets.count":
					assert.False(t, validatedMetrics["playwright.targets.count"], "Found a duplicate in the metrics slice: playwright.targets.count")
					validatedMetrics["playwright.targets.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active targets reported by Playwright.", ms.At(i).Description())
					assert.Equal(t, "{target}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("playwright.endpoint")
					assert.True(t, ok)
					assert.Equal(t, "playwright.endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("target.type")
					assert.True(t, ok)
					assert.Equal(t, "target.type-val", attrVal.Str())
				}
			}
		})
	}
}
