// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for chromium metrics.
type MetricsConfig struct {
	ChromiumPageDocumentCount        MetricConfig `mapstructure:"chromium.page.document.count"`
	ChromiumPageDomNodeCount         MetricConfig `mapstructure:"chromium.page.dom_node.count"`
	ChromiumPageFrameCount           MetricConfig `mapstructure:"chromium.page.frame.count"`
	ChromiumPageJsEventListenerCount MetricConfig `mapstructure:"chromium.page.js_event_listener.count"`
	ChromiumPageJsHeapTotalSize      MetricConfig `mapstructure:"chromium.page.js_heap.total_size"`
	ChromiumPageJsHeapUsedSize       MetricConfig `mapstructure:"chromium.page.js_heap.used_size"`
	ChromiumPageLayoutCount          MetricConfig `mapstructure:"chromium.page.layout.count"`
	ChromiumPageLayoutDuration       MetricConfig `mapstructure:"chromium.page.layout.duration"`
	ChromiumPageRecalcStyleCount     MetricConfig `mapstructure:"chromium.page.recalc_style.count"`
	ChromiumPageRecalcStyleDuration  MetricConfig `mapstructure:"chromium.page.recalc_style.duration"`
	ChromiumPageScriptDuration       MetricConfig `mapstructure:"chromium.page.script.duration"`
	ChromiumPageTaskDuration         MetricConfig `mapstructure:"chromium.page.task.duration"`
	ChromiumTargetsCount             MetricConfig `mapstructure:"chromium.targets.count"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		ChromiumPageDocumentCount: MetricConfig{
			Enabled: true,
		},
		ChromiumPageDomNodeCount: MetricConfig{
			Enabled: true,
		},
		ChromiumPageFrameCount: MetricConfig{
			Enabled: true,
		},
		ChromiumPageJsEventListenerCount: MetricConfig{
			Enabled: true,
		},
		ChromiumPageJsHeapTotalSize: MetricConfig{
			Enabled: true,
		},
		ChromiumPageJsHeapUsedSize: MetricConfig{
			Enabled: true,
		},
		ChromiumPageLayoutCount: MetricConfig{
			Enabled: true,
		},
		ChromiumPageLayoutDuration: MetricConfig{
			Enabled: true,
		},
		ChromiumPageRecalcStyleCount: MetricConfig{
			Enabled: true,
		},
		ChromiumPageRecalcStyleDuration: MetricConfig{
			Enabled: true,
		},
		ChromiumPageScriptDuration: MetricConfig{
			Enabled: true,
		},
		ChromiumPageTaskDuration: MetricConfig{
			Enabled: true,
		},
		ChromiumTargetsCount: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for chromium metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
