// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

var MetricsInfo = metricsInfo{
	ChromiumPageDocumentCount: metricInfo{
		Name: "chromium.page.document.count",
	},
	ChromiumPageDomNodeCount: metricInfo{
		Name: "chromium.page.dom_node.count",
	},
	ChromiumPageFrameCount: metricInfo{
		Name: "chromium.page.frame.count",
	},
	ChromiumPageJsEventListenerCount: metricInfo{
		Name: "chromium.page.js_event_listener.count",
	},
	ChromiumPageJsHeapTotalSize: metricInfo{
		Name: "chromium.page.js_heap.total_size",
	},
	ChromiumPageJsHeapUsedSize: metricInfo{
		Name: "chromium.page.js_heap.used_size",
	},
	ChromiumPageLayoutCount: metricInfo{
		Name: "chromium.page.layout.count",
	},
	ChromiumPageLayoutDuration: metricInfo{
		Name: "chromium.page.layout.duration",
	},
	ChromiumPageRecalcStyleCount: metricInfo{
		Name: "chromium.page.recalc_style.count",
	},
	ChromiumPageRecalcStyleDuration: metricInfo{
		Name: "chromium.page.recalc_style.duration",
	},
	ChromiumPageScriptDuration: metricInfo{
		Name: "chromium.page.script.duration",
	},
	ChromiumPageTaskDuration: metricInfo{
		Name: "chromium.page.task.duration",
	},
	ChromiumTargetsCount: metricInfo{
		Name: "chromium.targets.count",
	},
}

type metricsInfo struct {
	ChromiumPageDocumentCount        metricInfo
	ChromiumPageDomNodeCount         metricInfo
	ChromiumPageFrameCount           metricInfo
	ChromiumPageJsEventListenerCount metricInfo
	ChromiumPageJsHeapTotalSize      metricInfo
	ChromiumPageJsHeapUsedSize       metricInfo
	ChromiumPageLayoutCount          metricInfo
	ChromiumPageLayoutDuration       metricInfo
	ChromiumPageRecalcStyleCount     metricInfo
	ChromiumPageRecalcStyleDuration  metricInfo
	ChromiumPageScriptDuration       metricInfo
	ChromiumPageTaskDuration         metricInfo
	ChromiumTargetsCount             metricInfo
}

type metricInfo struct {
	Name string
}

type metricChromiumPageDocumentCount struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.page.document.count metric with initial data.
func (m *metricChromiumPageDocumentCount) init() {
	m.data.SetName("chromium.page.document.count")
	m.data.SetDescription("Number of documents in the page.")
	m.data.SetUnit("{document}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumPageDocumentCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
	dp.Attributes().PutStr("target.url", targetURLAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumPageDocumentCount) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumPageDocumentCount) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumPageDocumentCount(cfg MetricConfig) metricChromiumPageDocumentCount {
	m := metricChromiumPageDocumentCount{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricChromiumPageDomNodeCount struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.page.dom_node.count metric with initial data.
func (m *metricChromiumPageDomNodeCount) init() {
	m.data.SetName("chromium.page.dom_node.count")
	m.data.SetDescription("Number of DOM nodes in the page.")
	m.data.SetUnit("{node}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumPageDomNodeCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
	dp.Attributes().PutStr("target.url", targetURLAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumPageDomNodeCount) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumPageDomNodeCount) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumPageDomNodeCount(cfg MetricConfig) metricChromiumPageDomNodeCount {
	m := metricChromiumPageDomNodeCount{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricChromiumPageFrameCount struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.page.frame.count metric with initial data.
func (m *metricChromiumPageFrameCount) init() {
	m.data.SetName("chromium.page.frame.count")
	m.data.SetDescription("Number of frames in the page.")
	m.data.SetUnit("{frame}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumPageFrameCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
	dp.Attributes().PutStr("target.url", targetURLAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumPageFrameCount) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumPageFrameCount) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumPageFrameCount(cfg MetricConfig) metricChromiumPageFrameCount {
	m := metricChromiumPageFrameCount{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricChromiumPageJsEventListenerCount struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.page.js_event_listener.count metric with initial data.
func (m *metricChromiumPageJsEventListenerCount) init() {
	m.data.SetName("chromium.page.js_event_listener.count")
	m.data.SetDescription("Number of JavaScript event listeners in the page.")
	m.data.SetUnit("{listener}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumPageJsEventListenerCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
	dp.Attributes().PutStr("target.url", targetURLAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumPageJsEventListenerCount) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumPageJsEventListenerCount) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumPageJsEventListenerCount(cfg MetricConfig) metricChromiumPageJsEventListenerCount {
	m := metricChromiumPageJsEventListenerCount{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricChromiumPageJsHeapTotalSize struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.page.js_heap.total_size metric with initial data.
func (m *metricChromiumPageJsHeapTotalSize) init() {
	m.data.SetName("chromium.page.js_heap.total_size")
	m.data.SetDescription("Total JavaScript heap size.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumPageJsHeapTotalSize) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
	dp.Attributes().PutStr("target.url", targetURLAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumPageJsHeapTotalSize) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumPageJsHeapTotalSize) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumPageJsHeapTotalSize(cfg MetricConfig) metricChromiumPageJsHeapTotalSize {
	m := metricChromiumPageJsHeapTotalSize{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricChromiumPageJsHeapUsedSize struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.page.js_heap.used_size metric with initial data.
func (m *metricChromiumPageJsHeapUsedSize) init() {
	m.data.SetName("chromium.page.js_heap.used_size")
	m.data.SetDescription("Used JavaScript heap size.")
	m.data.SetUnit("By")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumPageJsHeapUsedSize) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
	dp.Attributes().PutStr("target.url", targetURLAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumPageJsHeapUsedSize) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumPageJsHeapUsedSize) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumPageJsHeapUsedSize(cfg MetricConfig) metricChromiumPageJsHeapUsedSize {
	m := metricChromiumPageJsHeapUsedSize{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricChromiumPageLayoutCount struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.page.layout.count metric with initial data.
func (m *metricChromiumPageLayoutCount) init() {
	m.data.SetName("chromium.page.layout.count")
	m.data.SetDescription("Cumulative count of full or partial page layouts.")
	m.data.SetUnit("{layout}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumPageLayoutCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
	dp.Attributes().PutStr("target.url", targetURLAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumPageLayoutCount) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumPageLayoutCount) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumPageLayoutCount(cfg MetricConfig) metricChromiumPageLayoutCount {
	m := metricChromiumPageLayoutCount{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricChromiumPageLayoutDuration struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.page.layout.duration metric with initial data.
func (m *metricChromiumPageLayoutDuration) init() {
	m.data.SetName("chromium.page.layout.duration")
	m.data.SetDescription("Cumulative duration of page layout operations.")
	m.data.SetUnit("s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumPageLayoutDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
	dp.Attributes().PutStr("target.url", targetURLAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumPageLayoutDuration) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumPageLayoutDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumPageLayoutDuration(cfg MetricConfig) metricChromiumPageLayoutDuration {
	m := metricChromiumPageLayoutDuration{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricChromiumPageRecalcStyleCount struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.page.recalc_style.count metric with initial data.
func (m *metricChromiumPageRecalcStyleCount) init() {
	m.data.SetName("chromium.page.recalc_style.count")
	m.data.SetDescription("Cumulative count of CSS style recalculations.")
	m.data.SetUnit("{recalculation}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumPageRecalcStyleCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
	dp.Attributes().PutStr("target.url", targetURLAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumPageRecalcStyleCount) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumPageRecalcStyleCount) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumPageRecalcStyleCount(cfg MetricConfig) metricChromiumPageRecalcStyleCount {
	m := metricChromiumPageRecalcStyleCount{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricChromiumPageRecalcStyleDuration struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.page.recalc_style.duration metric with initial data.
func (m *metricChromiumPageRecalcStyleDuration) init() {
	m.data.SetName("chromium.page.recalc_style.duration")
	m.data.SetDescription("Cumulative duration of CSS style recalculations.")
	m.data.SetUnit("s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumPageRecalcStyleDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
	dp.Attributes().PutStr("target.url", targetURLAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumPageRecalcStyleDuration) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumPageRecalcStyleDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumPageRecalcStyleDuration(cfg MetricConfig) metricChromiumPageRecalcStyleDuration {
	m := metricChromiumPageRecalcStyleDuration{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricChromiumPageScriptDuration struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.page.script.duration metric with initial data.
func (m *metricChromiumPageScriptDuration) init() {
	m.data.SetName("chromium.page.script.duration")
	m.data.SetDescription("Cumulative duration of JavaScript execution.")
	m.data.SetUnit("s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumPageScriptDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
	dp.Attributes().PutStr("target.url", targetURLAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumPageScriptDuration) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumPageScriptDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumPageScriptDuration(cfg MetricConfig) metricChromiumPageScriptDuration {
	m := metricChromiumPageScriptDuration{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricChromiumPageTaskDuration struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.page.task.duration metric with initial data.
func (m *metricChromiumPageTaskDuration) init() {
	m.data.SetName("chromium.page.task.duration")
	m.data.SetDescription("Cumulative duration of all tasks.")
	m.data.SetUnit("s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumPageTaskDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
	dp.Attributes().PutStr("target.url", targetURLAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumPageTaskDuration) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumPageTaskDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumPageTaskDuration(cfg MetricConfig) metricChromiumPageTaskDuration {
	m := metricChromiumPageTaskDuration{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricChromiumTargetsCount struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills chromium.targets.count metric with initial data.
func (m *metricChromiumTargetsCount) init() {
	m.data.SetName("chromium.targets.count")
	m.data.SetDescription("Number of active targets reported by Chromium.")
	m.data.SetUnit("{target}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricChromiumTargetsCount) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("chromium.endpoint", chromiumEndpointAttributeValue)
	dp.Attributes().PutStr("target.type", targetTypeAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricChromiumTargetsCount) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricChromiumTargetsCount) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricChromiumTargetsCount(cfg MetricConfig) metricChromiumTargetsCount {
	m := metricChromiumTargetsCount{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                                   MetricsBuilderConfig // config of the metrics builder.
	startTime                                pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                          int                  // maximum observed number of metrics per resource.
	metricsBuffer                            pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                                component.BuildInfo  // contains version information.
	metricChromiumPageDocumentCount        metricChromiumPageDocumentCount
	metricChromiumPageDomNodeCount         metricChromiumPageDomNodeCount
	metricChromiumPageFrameCount           metricChromiumPageFrameCount
	metricChromiumPageJsEventListenerCount metricChromiumPageJsEventListenerCount
	metricChromiumPageJsHeapTotalSize      metricChromiumPageJsHeapTotalSize
	metricChromiumPageJsHeapUsedSize       metricChromiumPageJsHeapUsedSize
	metricChromiumPageLayoutCount          metricChromiumPageLayoutCount
	metricChromiumPageLayoutDuration       metricChromiumPageLayoutDuration
	metricChromiumPageRecalcStyleCount     metricChromiumPageRecalcStyleCount
	metricChromiumPageRecalcStyleDuration  metricChromiumPageRecalcStyleDuration
	metricChromiumPageScriptDuration       metricChromiumPageScriptDuration
	metricChromiumPageTaskDuration         metricChromiumPageTaskDuration
	metricChromiumTargetsCount             metricChromiumTargetsCount
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                                   mbc,
		startTime:                                pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                            pmetric.NewMetrics(),
		buildInfo:                                settings.BuildInfo,
		metricChromiumPageDocumentCount:        newMetricChromiumPageDocumentCount(mbc.Metrics.ChromiumPageDocumentCount),
		metricChromiumPageDomNodeCount:         newMetricChromiumPageDomNodeCount(mbc.Metrics.ChromiumPageDomNodeCount),
		metricChromiumPageFrameCount:           newMetricChromiumPageFrameCount(mbc.Metrics.ChromiumPageFrameCount),
		metricChromiumPageJsEventListenerCount: newMetricChromiumPageJsEventListenerCount(mbc.Metrics.ChromiumPageJsEventListenerCount),
		metricChromiumPageJsHeapTotalSize:      newMetricChromiumPageJsHeapTotalSize(mbc.Metrics.ChromiumPageJsHeapTotalSize),
		metricChromiumPageJsHeapUsedSize:       newMetricChromiumPageJsHeapUsedSize(mbc.Metrics.ChromiumPageJsHeapUsedSize),
		metricChromiumPageLayoutCount:          newMetricChromiumPageLayoutCount(mbc.Metrics.ChromiumPageLayoutCount),
		metricChromiumPageLayoutDuration:       newMetricChromiumPageLayoutDuration(mbc.Metrics.ChromiumPageLayoutDuration),
		metricChromiumPageRecalcStyleCount:     newMetricChromiumPageRecalcStyleCount(mbc.Metrics.ChromiumPageRecalcStyleCount),
		metricChromiumPageRecalcStyleDuration:  newMetricChromiumPageRecalcStyleDuration(mbc.Metrics.ChromiumPageRecalcStyleDuration),
		metricChromiumPageScriptDuration:       newMetricChromiumPageScriptDuration(mbc.Metrics.ChromiumPageScriptDuration),
		metricChromiumPageTaskDuration:         newMetricChromiumPageTaskDuration(mbc.Metrics.ChromiumPageTaskDuration),
		metricChromiumTargetsCount:             newMetricChromiumTargetsCount(mbc.Metrics.ChromiumTargetsCount),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricChromiumPageDocumentCount.emit(ils.Metrics())
	mb.metricChromiumPageDomNodeCount.emit(ils.Metrics())
	mb.metricChromiumPageFrameCount.emit(ils.Metrics())
	mb.metricChromiumPageJsEventListenerCount.emit(ils.Metrics())
	mb.metricChromiumPageJsHeapTotalSize.emit(ils.Metrics())
	mb.metricChromiumPageJsHeapUsedSize.emit(ils.Metrics())
	mb.metricChromiumPageLayoutCount.emit(ils.Metrics())
	mb.metricChromiumPageLayoutDuration.emit(ils.Metrics())
	mb.metricChromiumPageRecalcStyleCount.emit(ils.Metrics())
	mb.metricChromiumPageRecalcStyleDuration.emit(ils.Metrics())
	mb.metricChromiumPageScriptDuration.emit(ils.Metrics())
	mb.metricChromiumPageTaskDuration.emit(ils.Metrics())
	mb.metricChromiumTargetsCount.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordChromiumPageDocumentCountDataPoint adds a data point to chromium.page.document.count metric.
func (mb *MetricsBuilder) RecordChromiumPageDocumentCountDataPoint(ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	mb.metricChromiumPageDocumentCount.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue, targetURLAttributeValue)
}

// RecordChromiumPageDomNodeCountDataPoint adds a data point to chromium.page.dom_node.count metric.
func (mb *MetricsBuilder) RecordChromiumPageDomNodeCountDataPoint(ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	mb.metricChromiumPageDomNodeCount.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue, targetURLAttributeValue)
}

// RecordChromiumPageFrameCountDataPoint adds a data point to chromium.page.frame.count metric.
func (mb *MetricsBuilder) RecordChromiumPageFrameCountDataPoint(ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	mb.metricChromiumPageFrameCount.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue, targetURLAttributeValue)
}

// RecordChromiumPageJsEventListenerCountDataPoint adds a data point to chromium.page.js_event_listener.count metric.
func (mb *MetricsBuilder) RecordChromiumPageJsEventListenerCountDataPoint(ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	mb.metricChromiumPageJsEventListenerCount.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue, targetURLAttributeValue)
}

// RecordChromiumPageJsHeapTotalSizeDataPoint adds a data point to chromium.page.js_heap.total_size metric.
func (mb *MetricsBuilder) RecordChromiumPageJsHeapTotalSizeDataPoint(ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	mb.metricChromiumPageJsHeapTotalSize.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue, targetURLAttributeValue)
}

// RecordChromiumPageJsHeapUsedSizeDataPoint adds a data point to chromium.page.js_heap.used_size metric.
func (mb *MetricsBuilder) RecordChromiumPageJsHeapUsedSizeDataPoint(ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	mb.metricChromiumPageJsHeapUsedSize.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue, targetURLAttributeValue)
}

// RecordChromiumPageLayoutCountDataPoint adds a data point to chromium.page.layout.count metric.
func (mb *MetricsBuilder) RecordChromiumPageLayoutCountDataPoint(ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	mb.metricChromiumPageLayoutCount.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue, targetURLAttributeValue)
}

// RecordChromiumPageLayoutDurationDataPoint adds a data point to chromium.page.layout.duration metric.
func (mb *MetricsBuilder) RecordChromiumPageLayoutDurationDataPoint(ts pcommon.Timestamp, val float64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	mb.metricChromiumPageLayoutDuration.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue, targetURLAttributeValue)
}

// RecordChromiumPageRecalcStyleCountDataPoint adds a data point to chromium.page.recalc_style.count metric.
func (mb *MetricsBuilder) RecordChromiumPageRecalcStyleCountDataPoint(ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	mb.metricChromiumPageRecalcStyleCount.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue, targetURLAttributeValue)
}

// RecordChromiumPageRecalcStyleDurationDataPoint adds a data point to chromium.page.recalc_style.duration metric.
func (mb *MetricsBuilder) RecordChromiumPageRecalcStyleDurationDataPoint(ts pcommon.Timestamp, val float64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	mb.metricChromiumPageRecalcStyleDuration.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue, targetURLAttributeValue)
}

// RecordChromiumPageScriptDurationDataPoint adds a data point to chromium.page.script.duration metric.
func (mb *MetricsBuilder) RecordChromiumPageScriptDurationDataPoint(ts pcommon.Timestamp, val float64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	mb.metricChromiumPageScriptDuration.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue, targetURLAttributeValue)
}

// RecordChromiumPageTaskDurationDataPoint adds a data point to chromium.page.task.duration metric.
func (mb *MetricsBuilder) RecordChromiumPageTaskDurationDataPoint(ts pcommon.Timestamp, val float64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string, targetURLAttributeValue string) {
	mb.metricChromiumPageTaskDuration.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue, targetURLAttributeValue)
}

// RecordChromiumTargetsCountDataPoint adds a data point to chromium.targets.count metric.
func (mb *MetricsBuilder) RecordChromiumTargetsCountDataPoint(ts pcommon.Timestamp, val int64, chromiumEndpointAttributeValue string, targetTypeAttributeValue string) {
	mb.metricChromiumTargetsCount.recordDataPoint(mb.startTime, ts, val, chromiumEndpointAttributeValue, targetTypeAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
