// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					ChromiumPageDocumentCount:        MetricConfig{Enabled: true},
					ChromiumPageDomNodeCount:         MetricConfig{Enabled: true},
					ChromiumPageFrameCount:           MetricConfig{Enabled: true},
					ChromiumPageJsEventListenerCount: MetricConfig{Enabled: true},
					ChromiumPageJsHeapTotalSize:      MetricConfig{Enabled: true},
					ChromiumPageJsHeapUsedSize:       MetricConfig{Enabled: true},
					ChromiumPageLayoutCount:          MetricConfig{Enabled: true},
					ChromiumPageLayoutDuration:       MetricConfig{Enabled: true},
					ChromiumPageRecalcStyleCount:     MetricConfig{Enabled: true},
					ChromiumPageRecalcStyleDuration:  MetricConfig{Enabled: true},
					ChromiumPageScriptDuration:       MetricConfig{Enabled: true},
					ChromiumPageTaskDuration:         MetricConfig{Enabled: true},
					ChromiumTargetsCount:             MetricConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					ChromiumPageDocumentCount:        MetricConfig{Enabled: false},
					ChromiumPageDomNodeCount:         MetricConfig{Enabled: false},
					ChromiumPageFrameCount:           MetricConfig{Enabled: false},
					ChromiumPageJsEventListenerCount: MetricConfig{Enabled: false},
					ChromiumPageJsHeapTotalSize:      MetricConfig{Enabled: false},
					ChromiumPageJsHeapUsedSize:       MetricConfig{Enabled: false},
					ChromiumPageLayoutCount:          MetricConfig{Enabled: false},
					ChromiumPageLayoutDuration:       MetricConfig{Enabled: false},
					ChromiumPageRecalcStyleCount:     MetricConfig{Enabled: false},
					ChromiumPageRecalcStyleDuration:  MetricConfig{Enabled: false},
					ChromiumPageScriptDuration:       MetricConfig{Enabled: false},
					ChromiumPageTaskDuration:         MetricConfig{Enabled: false},
					ChromiumTargetsCount:             MetricConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
